release:
  verifyConditions:
  - { path: "@semantic-release/changelog", changelogFile: "../CHANGELOG.md" }
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - "@semantic-release/github"
  publish:
  - { path: "@semantic-release/changelog", changelogFile: "../CHANGELOG.md" }
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - "@semantic-release/github"
