language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
script:
  - npm run dist
after_success:
  - cd dist && ../node_modules/.bin/travis-deploy-once "../node_modules/.bin/semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
