language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '9'
- '8'
script:
- npm run dist
after_success:
- npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: firebase
  token:
    secure: "WXwGqApwMOlVNsJurwVV+UX8pDkOgj//TpWyeVuRmnkQqc5FEo00TxJT1SbnxjXNdEDv2iz35IaOpO9sy2qlFnmIxPwtHfKcEVW2HzFWRwvFucbbSRdCnw+QgaO9//EAj4tZYvO18wpzVZKyVnmeCOJ6sWuRb9fvqeHXlzd+RukfGEoNaXjBatJIepI47EiJ2wAf+EyZxG+xGD1pF9/ZEa9Ktm3IwwANJOWoZ5UJ6nreBVHmqz4P6Sr/APapcm5l85FXwf3QightXWyQDBeQj3OqoID/61IFl4jDAmcoChXnXnYabYdm+0JE5yDhFyA2W7YBRTMJJXGjN4/ba5+JuMz0JyNkHnkgWuf8F0XYW+gGz5k36GyWKAcgyGu0z8Rid4DSNKsf1NbV5tz46jRKFstfkEDNapNMzzBWo7AqPYtY4qyDzEYdxQqX6l/h+AlWb6nqevjw38EjkkJOs9rzrZyUY67m8s7BqcewMS7hvzRJb+XWHGxspsAjLn3rS9+oZ+96mXKyI9yPHDjHUPIQ/pz7SJlqbNEkwBVs15uoYAbw2Y8QKtlrpfmr1y9bnvn+m4w3YEfoChk94OaWbpRicxHC0wXeUjUWrFXaAep773vc5BYrZCElfTc3phVpau+C0v8fjdwBNLxnRTmKPu1hNYJWNWCm0fseFJmzCnOwnxY="
  project: ngx-draft-js-demo-6aa62
